apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: redis-deploy
  labels:
    component: redis
    app: todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
      component: redis
  template:
    metadata:
      labels:
        app: todo
        component: redis
    spec:
      containers:
      - name: redis-deploy
        image: redis
        ports:
        - containerPort: 6379
        resources:
          limits:
            cpu: 300m
        args:
        - redis-server 
        - --requirepass ccp2 
        - --appendonly yes
